#ifndef FLAPPYBIRDS_DEFINITIONS_H
#define FLAPPYBIRDS_DEFINITIONS_H

#define SCREEN_WIDTH 768
#define SCREEN_HEIGHT 1024

#define INTRO_STATE_SHOW_TIME 3.0
#define INTRO_SCENE_BACKGROUND_FILEPATH "Resources/res/Splash.png"

#endif